/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#72b21d",
        "outline": "#757575",
        "on-secondary-fixed": "#3c4300",
        "tertiary-fixed": "#5cf7e5",
        "error-container": "#b92902",
        "primary-dim": "#9cdf4a",
        "secondary": "#dbed63",
        "outline-variant": "#484848",
        "tertiary": "#9ffff1",
        "error-dim": "#d53d18",
        "secondary-fixed": "#dbed63",
        "on-error-container": "#ffd2c8",
        "on-background": "#ffffff",
        "surface": "#0e0e0e",
        "on-primary": "#325600",
        "on-secondary-fixed-variant": "#566100",
        "primary-fixed": "#a9ee57",
        "inverse-primary": "#406a00",
        "surface-container-lowest": "#000000",
        "error": "#ff7351",
        "on-primary-fixed-variant": "#396000",
        "inverse-surface": "#f9f9f9",
        "surface-container-high": "#1f1f1f",
        "surface-variant": "#262626",
        "secondary-container": "#596400",
        "on-surface-variant": "#ababab",
        "on-secondary-container": "#f4ffa6",
        "on-primary-container": "#152800",
        "on-tertiary-fixed": "#00463f",
        "on-error": "#450900",
        "surface-container-low": "#131313",
        "on-tertiary": "#00645b",
        "surface-bright": "#2c2c2c",
        "surface-container": "#191919",
        "surface-container-highest": "#262626",
        "primary-fixed-dim": "#9cdf4a",
        "inverse-on-surface": "#555555",
        "tertiary-dim": "#45e5d4",
        "surface-tint": "#a9ee57",
        "surface-dim": "#0e0e0e",
        "background": "#0e0e0e",
        "on-tertiary-container": "#005a52",
        "tertiary-container": "#5cf7e5",
        "tertiary-fixed-dim": "#49e8d7",
        "secondary-fixed-dim": "#cdde56",
        "on-secondary": "#4d5700",
        "on-tertiary-fixed-variant": "#00655c",
        "secondary-dim": "#cdde56",
        "on-surface": "#ffffff",
        "on-primary-fixed": "#254100",
        "primary": "#a9ee57"
      },
      fontFamily: {
        "headline": ["Urbanist", "sans-serif"],
        "body": ["Urbanist", "sans-serif"],
        "label": ["Urbanist", "sans-serif"],
        "plus-jakarta": ["Plus Jakarta Sans", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
